### ISSUE TITLE
set dynamic id

### ISSUE THREAD

**Issue by TomWhitson** [sandunangelo/jquery-timesetter#4]
if there are multiple time setters on  a page the ids of inputs are set to the same value (txtHours, txtMinutes). is there a way to set a logical id or use name or some other attribute.

**Comment by sandunangelo** [comment]
Hi @TomWhitson ,

This where your jQuery skills matters, use your own container with your own unique Id assigned and find the plugin elements only within the container. It is up to you to limit one plugin element should be inside one container, so you can easily refer to the correct plugin element.

Happy coding!
